### ISSUE TITLE
error when refreshing and back-ing during game

### ISSUE THREAD

**Issue by adamperer** [cmuvis/mlint#24] opened 2019-11-06 16:34 UTC
![Screen Shot 2019-11-06 at 11 33 07 AM](https://user-images.githubusercontent.com/1194662/68317522-49fc1c00-0089-11ea-887b-3276dc7ba4a6.png)

TypeError: undefined is not an object (evaluating 'this.state.players[i].img')
generateProfiles
src/guessai/profile.js:121
  118 | <div className="playerNum">
  119 |     Player {i + 1}
  120 | </div>
> 121 | <div className="photo " >
      | ^  122 |     {this.state.players[i].img}</div>
  123 | <div className="name">
  124 |     {this.state.players[i].name}
View compiled
render
src/guessai/profile.js:136
  133 | return (
  134 | 
  135 |     <div className="profileWrapper">
> 136 |         <div className="profiles">
      | ^  137 |             {this.generateProfiles()}
  138 |         </div>
  139 |     </div>
View compiled
▶ 14 stack frames were collapsed.
./src/index.js
src/index.js:7
   4 | import App from './App';
   5 | import * as serviceWorker from './serviceWorker';
   6 | 
>  7 | ReactDOM.render(<App />, document.getElementById('root'));
   8 | 
   9 | // If you want your app to work offline and load faster, you can change
  10 | // unregister() to register() below. Note this comes with some pitfalls.
View compiled
__webpack_require__
/app/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
fn
/app/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
(anonymous function)
http://ai-gwap.appspot.com/static/js/main.chunk.js:12389:37
__webpack_require__
/app/webpack/bootstrap:781
  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;
View compiled
checkDeferredModules
/app/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | return result;
View compiled
webpackJsonpCallback
/app/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
global code
http://ai-gwap.appspot.com/static/js/main.chunk.js:1:61

**Comment by yzd1998111** [comment] 2019-11-24 18:08
I coded a temporary fix for this issue. The back button works properly(won't break the page) but the refresh button is troublesome.  This bug is trickier than I expected because pressing the refresh button clears the state and props of react and it is hard to completely restore the state and props. 

I got the refresh button working properly on the home and guessai page but once the player profile starts to be rendered and the component starts to rely on the state variables to render, refreshing would break the page because each refresh wipes out the previously stored player info. 

Currently, I override the behavior of the refresh button to ask the user if they really wants to refresh, which could lead to unexpected behavior. In this phase, the game is paused if the user presses Cancel, it continues to work properly. If the user insists on pressing the reload, the bug would come up.

**Closed** 2020-01-22 22:29 UTC
Labels: bug
