### ISSUE TITLE
viz update required

### ISSUE THREAD

**Issue by jayolee** [cmuvis/mlint#3] opened 2019-09-27 05:18 UTC
Couldn't update the viz since we need to save the file according to the coordination number.

**Comment by laurafulton** [comment] 2019-10-13 20:40
Examples of this (shows up not just in selection screen, error persists in other parts of game (see second image)):
<img width="865" alt="Screen Shot 2019-10-13 at 4 39 43 PM" src="https://user-images.githubusercontent.com/9020517/66722144-13a7e580-edd8-11e9-823f-7aa19940866d.png">
<img width="1005" alt="Screen Shot 2019-10-13 at 3 59 22 PM" src="https://user-images.githubusercontent.com/9020517/66722156-32a67780-edd8-11e9-9d4b-c68be09b9066.png">

**Comment by yzd1998111** [comment] 2019-10-28 04:12
The cause of this issue is that the correct/wrong hint image numbers are hardcoded but some of them cannot be found in the img directory. I marked them in the file to be fixed later.

**Comment by shivanggupta** [comment] 2019-10-29 01:49
Hi all, I've been completely swamped at my new job and had a lot of trouble
with my new apartment so I didnt have time to take a look at this earlier,
from a quick glance it looks like the issue is that the repo has my old
code and not the latest bug fixed code but I need to check. I can take a
look at this on Saturday and get back to you. Thanks for your patience and
sorry about the delay!

**Comment by shivanggupta** [comment] 2019-11-04 03:36
I'm unable to fix the code on the repo itself but it's working on my laptop, could @laurafulton or @yzd1998111 please give me a call and I will share the fix with them directly so they can update it. I will be in a design sprint all week but I can be reached by email and I'll share my phone number, I can talk after 5 pm on any day this week.

**Comment by adamperer** [comment] 2019-11-04 14:46
@yzd1998111 do you have time one night this week to discuss this issue with @shivanggupta ?  If so, @shivanggupta , please share your contact info.

For context, @yzd1998111 , this is the issue where the numbers were higher than the images we had. For now, you had replaced those higher numbers manually.  This should be a fix for that issue.

**Comment by yzd1998111** [comment] 2019-11-23 19:07
When would you be available next week? @shivanggupta

**Closed** 2020-01-22 19:15 UTC
Labels: bug
